import jsPDF from "jspdf";
import { saveJsPdf } from "@/lib/pdf";

type RGB = [number, number, number];

const ACCENT: RGB = [212, 162, 86];
const MUTED: RGB = [138, 126, 109];
const BG: RGB = [26, 23, 20];
const BG_SOFT: RGB = [40, 35, 28];
const TEXT: RGB = [245, 240, 232];
const HIGHLIGHT_BG: RGB = [
  Math.round(BG[0] + (ACCENT[0] - BG[0]) * 0.18),
  Math.round(BG[1] + (ACCENT[1] - BG[1]) * 0.18),
  Math.round(BG[2] + (ACCENT[2] - BG[2]) * 0.18),
];

const PAGE_W = 297;
const PAGE_H = 210;
const MARGIN = 18;

export interface PresentationWhisky {
  id: string;
  name: string;
  distillery?: string | null;
  region?: string | null;
  age?: number | null;
  abv?: number | null;
  avgOverall: number | null;
  avgNose: number | null;
  avgTaste: number | null;
  avgFinish: number | null;
  ratingCount: number;
}

export interface PresentationParticipant {
  id: string;
  name: string;
}

export interface PresentationData {
  tasting: {
    id: string;
    title: string;
    date?: string | null;
    location?: string | null;
    ratingScale?: number | null;
  };
  whiskies: PresentationWhisky[];
  participants: PresentationParticipant[];
  highlights?: {
    mostAgreed?: { name: string; stdDev: number } | null;
    mostDebated?: { name: string; stdDev: number } | null;
    mostGenerous?: { name: string; avg: number } | null;
    toughest?: { name: string; avg: number } | null;
    highestSingle?: { value: number; whiskyName: string } | null;
  };
  scaleMax: number;
  t: (key: string, opts?: { defaultValue?: string }) => string;
}

function paintBackground(doc: jsPDF) {
  doc.setFillColor(...BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, "F");
}

function drawAccentLine(doc: jsPDF, x: number, y: number, w: number) {
  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(0.5);
  doc.line(x, y, x + w, y);
}

function drawFooter(doc: jsPDF, page: number, total: number, t: PresentationData["t"], title: string) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(t("resultsUi.generatedBy", { defaultValue: "Generated by CaskSense Labs" }), MARGIN, PAGE_H - 8);
  doc.text(`${page} / ${total}`, PAGE_W - MARGIN, PAGE_H - 8, { align: "right" });
  if (page > 1) {
    doc.text(title, PAGE_W / 2, PAGE_H - 8, { align: "center" });
  }
}

function fmtScore(v: number | null | undefined, max: number): string {
  if (v == null) return "—";
  if (max === 100) return `${Math.round(v)}`;
  return v.toFixed(1);
}

function truncate(s: string, max: number): string {
  if (!s) return "";
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

function drawCoverSlide(doc: jsPDF, data: PresentationData) {
  paintBackground(doc);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...ACCENT);
  doc.text("CASKSENSE LABS", PAGE_W / 2, 38, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(34);
  doc.setTextColor(...TEXT);
  const titleLines = doc.splitTextToSize(data.tasting.title || "Tasting", PAGE_W - MARGIN * 4);
  doc.text(titleLines, PAGE_W / 2, 70, { align: "center" });

  drawAccentLine(doc, PAGE_W / 2 - 30, 88, 60);

  const metaParts: string[] = [];
  if (data.tasting.date) metaParts.push(data.tasting.date);
  if (data.tasting.location) metaParts.push(data.tasting.location);
  metaParts.push(data.t("resultsUi.metaParticipants", { defaultValue: `${data.participants.length} participants` }).replace("{{count}}", String(data.participants.length)));
  metaParts.push(`${data.whiskies.length} ${data.whiskies.length === 1 ? data.t("resultsUi.whisky", { defaultValue: "Whisky" }) : data.t("resultsUi.whiskies", { defaultValue: "Whiskies" })}`);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(...MUTED);
  doc.text(metaParts.join("  ·  "), PAGE_W / 2, 102, { align: "center" });

  doc.setFont("helvetica", "italic");
  doc.setFontSize(11);
  doc.setTextColor(...ACCENT);
  doc.text(data.t("resultsUi.downloadPresentationTitle", { defaultValue: "Präsentations-PDF" }), PAGE_W / 2, PAGE_H - 28, { align: "center" });
}

function drawLineupSlide(doc: jsPDF, data: PresentationData) {
  paintBackground(doc);
  drawSlideHeader(doc, data.t("resultsUi.theTasting", { defaultValue: "The Tasting" }), data.t("resultsUi.theTastingDesc", { defaultValue: "Tonight's lineup" }));

  const cols = Math.min(2, Math.max(1, Math.ceil(data.whiskies.length / 6)));
  const itemsPerCol = Math.ceil(data.whiskies.length / cols);
  const colW = (PAGE_W - MARGIN * 2 - (cols - 1) * 8) / cols;
  const lineH = 11;
  let yStart = 60;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  data.whiskies.forEach((w, idx) => {
    const colIdx = Math.floor(idx / itemsPerCol);
    const rowIdx = idx % itemsPerCol;
    const x = MARGIN + colIdx * (colW + 8);
    const y = yStart + rowIdx * lineH;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...ACCENT);
    doc.text(`#${idx + 1}`, x, y);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(...TEXT);
    doc.text(truncate(w.name, 36), x + 14, y);

    if (w.distillery) {
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      doc.text(truncate(w.distillery, 40), x + 14, y + 4.5);
    }
  });
}

function drawSlideHeader(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...ACCENT);
  doc.text(title.toUpperCase(), MARGIN, 22);
  drawAccentLine(doc, MARGIN, 26, 30);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...MUTED);
    doc.text(subtitle, MARGIN, 38);
  }
}

function drawHighlightsSlide(doc: jsPDF, data: PresentationData) {
  paintBackground(doc);
  drawSlideHeader(doc, data.t("resultsUi.section.overview", { defaultValue: "Highlights" }));

  const items: { label: string; value: string; sub?: string }[] = [];
  const h = data.highlights || {};
  if (h.mostAgreed) items.push({ label: data.t("resultsUi.highlights.biggestAgreement", { defaultValue: "Most Agreed" }), value: h.mostAgreed.name, sub: `σ = ${h.mostAgreed.stdDev.toFixed(1)}` });
  if (h.mostDebated) items.push({ label: data.t("resultsUi.highlights.biggestDispute", { defaultValue: "Most Debated" }), value: h.mostDebated.name, sub: `σ = ${h.mostDebated.stdDev.toFixed(1)}` });
  if (h.mostGenerous) items.push({ label: data.t("resultsUi.awards.mostGenerous", { defaultValue: "Most Generous" }), value: h.mostGenerous.name, sub: `Ø ${fmtScore(h.mostGenerous.avg, data.scaleMax)}` });
  if (h.toughest) items.push({ label: data.t("resultsUi.awards.strictest", { defaultValue: "Toughest Critic" }), value: h.toughest.name, sub: `Ø ${fmtScore(h.toughest.avg, data.scaleMax)}` });
  if (h.highestSingle) items.push({ label: data.t("resultsUi.stats.highestRating", { defaultValue: "Highest Rating" }), value: h.highestSingle.whiskyName, sub: `${h.highestSingle.value}` });

  if (items.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.setTextColor(...MUTED);
    doc.text(data.t("resultsUi.heatmap.empty", { defaultValue: "No highlights yet" }), PAGE_W / 2, PAGE_H / 2, { align: "center" });
    return;
  }

  const cardsPerRow = Math.min(3, items.length);
  const rows = Math.ceil(items.length / cardsPerRow);
  const cardW = (PAGE_W - MARGIN * 2 - (cardsPerRow - 1) * 8) / cardsPerRow;
  const cardH = 36;
  const yStart = 56;

  items.forEach((item, idx) => {
    const col = idx % cardsPerRow;
    const row = Math.floor(idx / cardsPerRow);
    const x = MARGIN + col * (cardW + 8);
    const y = yStart + row * (cardH + 8);

    doc.setFillColor(...BG_SOFT);
    doc.roundedRect(x, y, cardW, cardH, 3, 3, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    doc.text(item.label.toUpperCase(), x + 6, y + 8);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...TEXT);
    const valueLines = doc.splitTextToSize(item.value, cardW - 12);
    doc.text(valueLines.slice(0, 2), x + 6, y + 18);

    if (item.sub) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...ACCENT);
      doc.text(item.sub, x + 6, y + cardH - 5);
    }

    if (rows === 1 && idx === items.length - 1) return;
  });
}

function drawWhiskySlide(doc: jsPDF, data: PresentationData, w: PresentationWhisky, rank: number) {
  paintBackground(doc);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...ACCENT);
  const rankLabel = rank === 1
    ? data.t("resultsUi.andTheWinnerIs", { defaultValue: "The Winner" })
    : data.t("resultsUi.theTasting", { defaultValue: "The Tasting" });
  doc.text(`#${rank}  ·  ${rankLabel.toUpperCase()}`, MARGIN, 22);
  drawAccentLine(doc, MARGIN, 26, 36);

  const isPodium = rank <= 3;
  if (isPodium) {
    doc.setFillColor(...HIGHLIGHT_BG);
    doc.roundedRect(MARGIN, 32, PAGE_W - MARGIN * 2, PAGE_H - 60, 4, 4, "F");
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(...TEXT);
  const nameLines = doc.splitTextToSize(w.name || "Unknown", PAGE_W - MARGIN * 2 - 80);
  doc.text(nameLines.slice(0, 2), MARGIN + 8, 60);

  if (w.distillery) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(13);
    doc.setTextColor(...MUTED);
    doc.text(truncate(w.distillery, 60), MARGIN + 8, 75);
  }

  const metaParts: string[] = [];
  if (w.region) metaParts.push(w.region);
  if (w.age) metaParts.push(`${w.age}y`);
  if (w.abv) metaParts.push(`${w.abv}%`);
  if (metaParts.length > 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...MUTED);
    doc.text(metaParts.join("  ·  "), MARGIN + 8, 84);
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(54);
  doc.setTextColor(...ACCENT);
  doc.text(fmtScore(w.avgOverall, data.scaleMax), PAGE_W - MARGIN - 12, 70, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  const ratingLabel = `${w.ratingCount} ${w.ratingCount === 1 ? data.t("resultsUi.rating", { defaultValue: "rating" }) : data.t("resultsUi.ratings", { defaultValue: "ratings" })}`;
  doc.text(ratingLabel, PAGE_W - MARGIN - 12, 78, { align: "right" });

  const dimY = 110;
  const dimLabels = [
    data.t("resultsUi.nose", { defaultValue: "Nose" }),
    data.t("resultsUi.taste", { defaultValue: "Taste" }),
    data.t("resultsUi.finish", { defaultValue: "Finish" }),
  ];
  const dimVals = [w.avgNose, w.avgTaste, w.avgFinish];
  const barW = PAGE_W - MARGIN * 2 - 16 - 80;

  dimLabels.forEach((label, i) => {
    const y = dimY + i * 18;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...TEXT);
    doc.text(label, MARGIN + 8, y);

    doc.setFillColor(60, 55, 45);
    doc.roundedRect(MARGIN + 8 + 30, y - 4, barW, 6, 1.5, 1.5, "F");

    const v = dimVals[i];
    if (v != null) {
      const pct = data.scaleMax > 0 ? Math.min(v, data.scaleMax) / data.scaleMax : 0;
      doc.setFillColor(...ACCENT);
      doc.roundedRect(MARGIN + 8 + 30, y - 4, barW * pct, 6, 1.5, 1.5, "F");
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...ACCENT);
    doc.text(fmtScore(v, data.scaleMax), PAGE_W - MARGIN - 12, y, { align: "right" });
  });
}

function drawPodiumSlide(doc: jsPDF, data: PresentationData) {
  paintBackground(doc);
  drawSlideHeader(doc, data.t("resultsUi.andTheWinnerIs", { defaultValue: "Podium" }));

  const top3 = data.whiskies.slice(0, 3);
  if (top3.length < 1) return;

  const heights = [70, 95, 55];
  const order = [1, 0, 2];
  const colW = 60;
  const totalW = colW * 3 + 10 * 2;
  const startX = (PAGE_W - totalW) / 2;
  const baseY = PAGE_H - 32;

  order.forEach((rankIdx, displayIdx) => {
    const w = top3[rankIdx];
    if (!w) return;
    const x = startX + displayIdx * (colW + 10);
    const h = heights[rankIdx];
    const y = baseY - h;

    const isWinner = rankIdx === 0;
    doc.setFillColor(...(isWinner ? ACCENT : HIGHLIGHT_BG));
    doc.roundedRect(x, y, colW, h, 3, 3, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.setTextColor(...(isWinner ? BG : ACCENT));
    doc.text(`#${rankIdx + 1}`, x + colW / 2, y + 22, { align: "center" });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...(isWinner ? BG : TEXT));
    const nameLines = doc.splitTextToSize(truncate(w.name || "—", 40), colW - 6);
    doc.text(nameLines.slice(0, 3), x + colW / 2, y + 38, { align: "center" });

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...(isWinner ? BG : ACCENT));
    doc.text(fmtScore(w.avgOverall, data.scaleMax), x + colW / 2, y + h - 6, { align: "center" });
  });
}

function drawOutroSlide(doc: jsPDF, data: PresentationData) {
  paintBackground(doc);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...ACCENT);
  doc.text("CASKSENSE LABS", PAGE_W / 2, 60, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(38);
  doc.setTextColor(...TEXT);
  doc.text(data.t("resultsUi.thanksTitle", { defaultValue: "Sláinte!" }), PAGE_W / 2, 100, { align: "center" });

  drawAccentLine(doc, PAGE_W / 2 - 30, 112, 60);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(...MUTED);
  doc.text(
    data.t("resultsUi.thanksSubtitle", { defaultValue: "Until the next dram." }),
    PAGE_W / 2,
    128,
    { align: "center" },
  );
}

export async function exportPresentationPdf(data: PresentationData): Promise<void> {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  const sorted = [...data.whiskies].sort((a, b) => (b.avgOverall ?? -Infinity) - (a.avgOverall ?? -Infinity));
  const sortedData: PresentationData = { ...data, whiskies: sorted };

  drawCoverSlide(doc, sortedData);

  if (sorted.length > 0) {
    doc.addPage("a4", "landscape");
    drawLineupSlide(doc, sortedData);
  }

  if (sortedData.highlights && Object.keys(sortedData.highlights).length > 0) {
    doc.addPage("a4", "landscape");
    drawHighlightsSlide(doc, sortedData);
  }

  const reversed = [...sorted].reverse();
  reversed.forEach((w, i) => {
    const rank = sorted.length - i;
    doc.addPage("a4", "landscape");
    drawWhiskySlide(doc, sortedData, w, rank);
  });

  if (sorted.length >= 3) {
    doc.addPage("a4", "landscape");
    drawPodiumSlide(doc, sortedData);
  }

  doc.addPage("a4", "landscape");
  drawOutroSlide(doc, sortedData);

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(doc, i, totalPages, data.t, data.tasting.title || "Tasting");
  }

  const safeName = (data.tasting.title || "presentation").replace(/[^a-zA-Z0-9]/g, "_");
  await saveJsPdf(doc, `${safeName}_presentation.pdf`);
}
