import { pidHeaders } from "@/lib/api";
import type { StoryBlock, StoryDocument } from "@/storybuilder/core/types";

export type TastingStoryDocument = StoryDocument;

export type TastingStoryMeta = {
  id: string;
  title: string;
  hostId: string | null;
  hostName: string | null;
  scheduledAt: string | null;
  location: string | null;
  coverImageUrl: string | null;
  storyEnabled: boolean;
  updatedAt: string | null;
};

export type TastingStoryResponse = {
  tasting: TastingStoryMeta;
  document: TastingStoryDocument;
  autoGenerated: boolean;
  canEdit: boolean;
};

export class TastingStoryApiError extends Error {
  status: number;
  constructor(status: number, message: string) {
    super(message);
    this.name = "TastingStoryApiError";
    this.status = status;
  }
}

async function readJson<T>(res: Response, fallback: string): Promise<T> {
  if (!res.ok) {
    let msg = fallback;
    try {
      const data = await res.json();
      if (data && typeof data.message === "string") msg = data.message;
    } catch {
      void 0;
    }
    throw new TastingStoryApiError(res.status, msg);
  }
  return (await res.json()) as T;
}

export async function getTastingStory(tastingId: string): Promise<TastingStoryResponse> {
  const res = await fetch(`/api/tasting-stories/${encodeURIComponent(tastingId)}`, {
    credentials: "include",
    headers: pidHeaders(),
  });
  return readJson<TastingStoryResponse>(res, "Story konnte nicht geladen werden");
}

export async function getPublicTastingStory(tastingId: string): Promise<TastingStoryResponse> {
  const res = await fetch(`/api/public/tasting-stories/${encodeURIComponent(tastingId)}`, {
    credentials: "include",
    headers: pidHeaders(),
  });
  return readJson<TastingStoryResponse>(res, "Story konnte nicht geladen werden");
}

export async function saveTastingStory(
  tastingId: string,
  blocks: StoryBlock[],
): Promise<{ ok: true; updatedAt: string }> {
  const res = await fetch(`/api/tasting-stories/${encodeURIComponent(tastingId)}`, {
    method: "PUT",
    credentials: "include",
    headers: { "Content-Type": "application/json", ...pidHeaders() },
    body: JSON.stringify({ blocks }),
  });
  return readJson(res, "Story konnte nicht gespeichert werden");
}

export async function snapshotTastingStory(
  tastingId: string,
  blocks: StoryBlock[],
  name?: string,
): Promise<{ id: string; createdAt: string }> {
  const res = await fetch(`/api/tasting-stories/${encodeURIComponent(tastingId)}/versions`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json", ...pidHeaders() },
    body: JSON.stringify({ blocks, name: name ?? undefined }),
  });
  return readJson(res, "Snapshot fehlgeschlagen");
}

export type WizardTone = "festive" | "casual" | "analytical" | "poetic";

export type WizardGenerateInput = {
  tone?: WizardTone | null;
  headlineOverride?: string | null;
  subtitleOverride?: string | null;
  heroImageUrl?: string | null;
  galleryImageUrls?: string[];
  spotlightParticipantIds?: string[];
  highlightContext?: string | null;
  overwriteExisting?: boolean;
};

export type WizardStep = {
  key: string;
  label: string;
  status: "pending" | "running" | "done" | "skipped" | "error";
};

export type WizardStartResponse = {
  jobId: string;
  steps: WizardStep[];
};

export type WizardProgressResponse = {
  jobId: string;
  status: "running" | "done" | "error";
  currentStepKey: string | null;
  completedSteps: number;
  totalSteps: number;
  steps: WizardStep[];
  error: string | null;
  blocks: StoryBlock[] | null;
};

export async function startTastingStoryWizard(
  tastingId: string,
  input: WizardGenerateInput,
): Promise<WizardStartResponse> {
  const res = await fetch(`/api/tasting-stories/${encodeURIComponent(tastingId)}/wizard-generate`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json", ...pidHeaders() },
    body: JSON.stringify(input),
  });
  return readJson<WizardStartResponse>(res, "Wizard konnte nicht gestartet werden");
}

export async function pollTastingStoryWizard(
  tastingId: string,
  jobId: string,
): Promise<WizardProgressResponse> {
  const url = `/api/tasting-stories/${encodeURIComponent(tastingId)}/wizard-progress?jobId=${encodeURIComponent(jobId)}`;
  const res = await fetch(url, {
    credentials: "include",
    headers: pidHeaders(),
  });
  return readJson<WizardProgressResponse>(res, "Status konnte nicht geladen werden");
}

export type WizardHeadlineSuggestion = {
  headline: string;
  subtitle: string;
};

export async function suggestTastingStoryHeadline(
  tastingId: string,
  tone: WizardTone | null,
): Promise<WizardHeadlineSuggestion> {
  const res = await fetch(`/api/tasting-stories/${encodeURIComponent(tastingId)}/wizard-suggest-headline`, {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json", ...pidHeaders() },
    body: JSON.stringify({ tone }),
  });
  return readJson<WizardHeadlineSuggestion>(res, "Vorschlag fehlgeschlagen");
}
