import { useQuery } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { ArrowLeft, Wine, Trophy, Users, Star, BarChart3, ChevronDown, ChevronUp, TrendingUp, TrendingDown, Minus, Target, MessageCircle, Award, Sparkles, Download, FileText, FileSpreadsheet, Loader2 } from "lucide-react";
import { useState, useMemo, useRef, useEffect } from "react";
import { useAppStore } from "@/lib/store";
import { tastingApi, whiskyApi, ratingApi } from "@/lib/api";
import { downloadBlob } from "@/lib/download";
import jsPDF from "jspdf";

async function labsExportFromServer(tastingId: string, format: "csv" | "xlsx"): Promise<boolean> {
  const res = await fetch(`/api/tastings/${tastingId}/results/export?format=${format}`);
  if (!res.ok) return false;
  const blob = await res.blob();
  const disp = res.headers.get("Content-Disposition");
  const filenameMatch = disp?.match(/filename="?([^"]+)"?/);
  const filename = filenameMatch?.[1] || `results.${format}`;
  downloadBlob(blob, filename);
  return true;
}

function labsExportPdf(tasting: any, whiskyResults: any[]) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = 210;
  const pageH = 297;
  const marginX = 18;
  const contentW = pageW - marginX * 2;
  const accent: [number, number, number] = [212, 162, 86];
  const dark: [number, number, number] = [30, 28, 24];
  const muted: [number, number, number] = [138, 126, 109];
  const bg: [number, number, number] = [26, 23, 20];
  const textColor: [number, number, number] = [245, 240, 232];

  const drawPageBg = () => {
    doc.setFillColor(...bg);
    doc.rect(0, 0, pageW, pageH, "F");
  };

  const drawHeader = () => {
    doc.setFillColor(...accent);
    doc.rect(0, 0, pageW, 3, "F");
  };

  const drawFooter = () => {
    const footerY = pageH - 12;
    doc.setDrawColor(...accent);
    doc.setLineWidth(0.3);
    doc.line(marginX, footerY - 4, pageW - marginX, footerY - 4);
    doc.setFontSize(7);
    doc.setTextColor(...muted);
    doc.text("Generated by CaskSense Labs", marginX, footerY);
    doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageW - marginX, footerY, { align: "right" });
  };

  drawPageBg();
  drawHeader();

  let y = 18;

  doc.setFontSize(10);
  doc.setTextColor(...accent);
  doc.setFont("helvetica", "bold");
  doc.text("CaskSense Labs", pageW / 2, y, { align: "center" });
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...textColor);
  doc.text(tasting.title || "Tasting Results", pageW / 2, y, { align: "center" });
  y += 9;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...muted);
  const totalRatings = whiskyResults.reduce((s, w) => s + w.ratingCount, 0);
  doc.text(
    `${whiskyResults.length} ${whiskyResults.length === 1 ? "whisky" : "whiskies"} \u00B7 ${totalRatings} ${totalRatings === 1 ? "rating" : "ratings"}`,
    pageW / 2, y, { align: "center" }
  );
  y += 8;

  doc.setDrawColor(...accent);
  doc.setLineWidth(0.5);
  doc.line(marginX, y, pageW - marginX, y);
  y += 10;

  const sorted = [...whiskyResults].sort((a, b) => (b.avgOverall || 0) - (a.avgOverall || 0));

  sorted.forEach((r, i) => {
    const blockH = 28;
    if (y + blockH > pageH - 20) {
      drawFooter();
      doc.addPage();
      drawPageBg();
      drawHeader();
      y = 18;
    }

    if (i < 3) {
      doc.setFillColor(
        Math.round(bg[0] + (accent[0] - bg[0]) * 0.12),
        Math.round(bg[1] + (accent[1] - bg[1]) * 0.12),
        Math.round(bg[2] + (accent[2] - bg[2]) * 0.12),
      );
      doc.roundedRect(marginX, y - 4, contentW, blockH - 2, 2, 2, "F");
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...(i < 3 ? accent : textColor));
    doc.text(`#${i + 1}`, marginX + 2, y + 2);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...textColor);
    const nameText = (r.name || "Unknown").length > 35 ? (r.name || "Unknown").slice(0, 33) + "\u2026" : (r.name || "Unknown");
    doc.text(nameText, marginX + 16, y + 2);

    if (r.distillery) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...muted);
      doc.text(r.distillery, marginX + 16, y + 7);
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...accent);
    doc.text(r.avgOverall?.toFixed?.(1) ?? String(r.avgOverall ?? "\u2014"), pageW - marginX, y + 3, { align: "right" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...muted);
    doc.text(`${r.ratingCount} ${r.ratingCount === 1 ? "rating" : "ratings"}`, pageW - marginX, y + 8, { align: "right" });

    const barY = y + 12;
    const barLabels = ["Nose", "Taste", "Finish", "Balance"];
    const barVals = [r.avgNose, r.avgTaste, r.avgFinish, r.avgBalance];
    const barMaxW = contentW - 50;

    barLabels.forEach((lbl, bi) => {
      const bx = marginX + 16;
      const by = barY + bi * 5;
      doc.setFontSize(6);
      doc.setTextColor(...muted);
      doc.text(lbl, bx, by + 1);
      doc.setFillColor(60, 55, 45);
      doc.roundedRect(bx + 24, by - 1.5, barMaxW * 0.25, 3, 1, 1, "F");
      if (barVals[bi] != null) {
        const pct = Math.min(barVals[bi]!, 100) / 100;
        doc.setFillColor(...accent);
        doc.roundedRect(bx + 24, by - 1.5, barMaxW * 0.25 * pct, 3, 1, 1, "F");
        doc.setFontSize(6);
        doc.setTextColor(...textColor);
        doc.text(String(barVals[bi]), bx + 26 + barMaxW * 0.25, by + 1);
      }
    });

    y += blockH + 4;
  });

  drawFooter();
  const safeName = (tasting.title || "results").replace(/[^a-zA-Z0-9]/g, "_");
  doc.save(`${safeName}_results.pdf`);
}

function LabsExportDropdown({ tastingId, tasting, whiskyResults }: { tastingId: string; tasting: any; whiskyResults: any[] }) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  const handleServerExport = async (format: "csv" | "xlsx") => {
    setLoading(format);
    try {
      await labsExportFromServer(tastingId, format);
    } finally {
      setLoading(null);
      setOpen(false);
    }
  };

  return (
    <div ref={ref} style={{ position: "relative", display: "inline-block" }}>
      <button
        className="labs-btn-secondary flex items-center gap-2"
        onClick={() => setOpen(!open)}
        data-testid="button-labs-export-menu"
      >
        <Download className="w-4 h-4" />
        Export
      </button>
      {open && (
        <div
          style={{
            position: "absolute",
            top: "calc(100% + 4px)",
            right: 0,
            background: "var(--labs-surface-elevated)",
            border: "1px solid var(--labs-border)",
            borderRadius: 10,
            padding: 6,
            minWidth: 160,
            zIndex: 50,
            boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
          }}
          data-testid="dropdown-labs-export-menu"
        >
          <button
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              width: "100%",
              padding: "8px 12px",
              background: "transparent",
              border: "none",
              borderRadius: 6,
              cursor: "pointer",
              color: "var(--labs-text)",
              fontSize: 13,
              fontFamily: "inherit",
              opacity: loading === "csv" ? 0.6 : 1,
            }}
            onClick={() => handleServerExport("csv")}
            disabled={loading === "csv"}
            data-testid="button-labs-export-csv"
          >
            {loading === "csv" ? <Loader2 style={{ width: 14, height: 14, animation: "spin 1s linear infinite" }} /> : <FileText style={{ width: 14, height: 14, color: "var(--labs-text-muted)" }} />}
            CSV
          </button>
          <button
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              width: "100%",
              padding: "8px 12px",
              background: "transparent",
              border: "none",
              borderRadius: 6,
              cursor: "pointer",
              color: "var(--labs-text)",
              fontSize: 13,
              fontFamily: "inherit",
              opacity: loading === "xlsx" ? 0.6 : 1,
            }}
            onClick={() => handleServerExport("xlsx")}
            disabled={loading === "xlsx"}
            data-testid="button-labs-export-excel"
          >
            {loading === "xlsx" ? <Loader2 style={{ width: 14, height: 14, animation: "spin 1s linear infinite" }} /> : <FileSpreadsheet style={{ width: 14, height: 14, color: "var(--labs-text-muted)" }} />}
            Excel
          </button>
          <button
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              width: "100%",
              padding: "8px 12px",
              background: "transparent",
              border: "none",
              borderRadius: 6,
              cursor: "pointer",
              color: "var(--labs-text)",
              fontSize: 13,
              fontFamily: "inherit",
            }}
            onClick={() => { labsExportPdf(tasting, whiskyResults); setOpen(false); }}
            data-testid="button-labs-export-pdf"
          >
            <Download style={{ width: 14, height: 14, color: "var(--labs-text-muted)" }} />
            PDF
          </button>
        </div>
      )}
    </div>
  );
}

interface LabsResultsProps {
  params: { id: string };
}

export default function LabsResults({ params }: LabsResultsProps) {
  const tastingId = params.id;
  const { currentParticipant } = useAppStore();
  const [, navigate] = useLocation();
  const [expandedWhisky, setExpandedWhisky] = useState<string | null>(null);

  const { data: tasting, isLoading: loadingTasting, isError: tastingError } = useQuery({
    queryKey: ["tasting", tastingId],
    queryFn: () => tastingApi.get(tastingId),
    enabled: !!tastingId,
  });

  const { data: whiskies, isLoading: loadingWhiskies } = useQuery({
    queryKey: ["whiskies", tastingId],
    queryFn: () => whiskyApi.getForTasting(tastingId),
    enabled: !!tastingId,
  });

  const { data: allRatings } = useQuery({
    queryKey: ["tastingRatings", tastingId],
    queryFn: () => ratingApi.getForTasting(tastingId),
    enabled: !!tastingId,
  });

  const { data: participants } = useQuery({
    queryKey: ["tastingParticipants", tastingId],
    queryFn: () => tastingApi.getParticipants(tastingId),
    enabled: !!tastingId,
  });

  const isLoading = loadingTasting || loadingWhiskies;

  const whiskyResults = useMemo(() => {
    return (whiskies || []).map((w: any) => {
      const ratings = (allRatings || []).filter((r: any) => r.whiskyId === w.id);
      const count = ratings.length;

      const avg = (dim: string) => {
        const vals = ratings.map((r: any) => r[dim]).filter((v: any) => v != null && v > 0);
        if (vals.length === 0) return null;
        return Math.round(vals.reduce((a: number, b: number) => a + b, 0) / vals.length);
      };

      const minMax = (dim: string) => {
        const vals = ratings.map((r: any) => r[dim]).filter((v: any) => v != null && v > 0);
        if (vals.length === 0) return { min: null, max: null, spread: null };
        const min = Math.min(...vals);
        const max = Math.max(...vals);
        return { min, max, spread: max - min };
      };

      const stdDev = (dim: string) => {
        const vals = ratings.map((r: any) => r[dim]).filter((v: any) => v != null && v > 0);
        if (vals.length < 2) return null;
        const mean = vals.reduce((a: number, b: number) => a + b, 0) / vals.length;
        const variance = vals.reduce((sum: number, v: number) => sum + (v - mean) ** 2, 0) / vals.length;
        return Math.sqrt(variance);
      };

      const avgOverall = avg("overall");
      const avgNose = avg("nose");
      const avgTaste = avg("taste");
      const avgFinish = avg("finish");
      const avgBalance = avg("balance");
      const overallRange = minMax("overall");
      const overallStdDev = stdDev("overall");

      const myRating = currentParticipant
        ? ratings.find((r: any) => r.participantId === currentParticipant.id)
        : null;

      const myDelta = myRating?.overall != null && avgOverall != null
        ? myRating.overall - avgOverall
        : null;

      return {
        ...w,
        ratings,
        ratingCount: count,
        avgOverall,
        avgNose,
        avgTaste,
        avgFinish,
        avgBalance,
        myRating,
        myDelta,
        overallRange,
        overallStdDev,
      };
    });
  }, [whiskies, allRatings, currentParticipant]);

  const sorted = useMemo(() => [...whiskyResults].sort((a, b) => (b.avgOverall || 0) - (a.avgOverall || 0)), [whiskyResults]);

  const summaryData = useMemo(() => {
    const rated = sorted.filter(w => w.avgOverall != null);
    const groupAvg = rated.length > 0
      ? Math.round(rated.reduce((s, w) => s + (w.avgOverall || 0), 0) / rated.length)
      : null;

    const myRated = sorted.filter(w => w.myRating?.overall != null);
    const userAvg = myRated.length > 0
      ? Math.round(myRated.reduce((s, w) => s + (w.myRating?.overall || 0), 0) / myRated.length)
      : null;

    const withStdDev = sorted.filter(w => w.overallStdDev != null && w.ratingCount >= 2);
    const mostAgreed = withStdDev.length > 0
      ? withStdDev.reduce((best, w) => (w.overallStdDev! < best.overallStdDev!) ? w : best)
      : null;
    const mostDebated = withStdDev.length > 0
      ? withStdDev.reduce((best, w) => (w.overallStdDev! > best.overallStdDev!) ? w : best)
      : null;

    const consensusWhiskies = withStdDev.filter(w => w.overallStdDev! <= 5);
    const debatedWhiskies = withStdDev.filter(w => w.overallStdDev! > 10);

    const myHighlights = myRated
      .filter(w => w.myDelta != null && w.myDelta > 5)
      .sort((a, b) => (b.myDelta || 0) - (a.myDelta || 0));

    const myLowlights = myRated
      .filter(w => w.myDelta != null && w.myDelta < -5)
      .sort((a, b) => (a.myDelta || 0) - (b.myDelta || 0));

    return { groupAvg, userAvg, mostAgreed, mostDebated, consensusWhiskies, debatedWhiskies, myHighlights, myLowlights };
  }, [sorted]);

  if (tastingError) {
    return (
      <div className="labs-empty labs-fade-in" style={{ minHeight: "60vh" }}>
        <Wine className="w-10 h-10 mb-3" style={{ color: "var(--labs-text-muted)" }} />
        <p className="text-base font-medium mb-2" style={{ color: "var(--labs-text)" }}>Results not available</p>
        <p className="text-sm mb-6" style={{ color: "var(--labs-text-muted)" }}>This tasting may have been removed or the link is incorrect.</p>
        <button
          className="labs-btn-secondary"
          onClick={() => navigate("/labs/tastings")}
          data-testid="results-error-back"
        >
          Back to Tastings
        </button>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="labs-empty labs-fade-in" style={{ minHeight: "60vh" }}>
        <div
          className="w-8 h-8 border-2 rounded-full animate-spin mb-4"
          style={{ borderColor: "var(--labs-border)", borderTopColor: "var(--labs-accent)" }}
        />
        <p className="text-sm" style={{ color: "var(--labs-text-muted)" }}>Loading results…</p>
      </div>
    );
  }

  if (!tasting) {
    return (
      <div className="labs-empty labs-fade-in" style={{ minHeight: "60vh" }}>
        <Wine className="w-10 h-10 mb-3" style={{ color: "var(--labs-text-muted)" }} />
        <p className="text-base font-medium mb-2" style={{ color: "var(--labs-text)" }}>Results not available</p>
        <p className="text-sm mb-6" style={{ color: "var(--labs-text-muted)" }}>This tasting could not be loaded.</p>
        <button
          className="labs-btn-secondary"
          onClick={() => navigate("/labs/tastings")}
          data-testid="results-back-tastings"
        >
          Back to Tastings
        </button>
      </div>
    );
  }

  const topWhisky = sorted[0];
  const participantCount = participants?.length || 0;
  const totalRatings = allRatings?.length || 0;

  const toggleExpand = (id: string) => {
    setExpandedWhisky(expandedWhisky === id ? null : id);
  };

  const DeltaIndicator = ({ delta }: { delta: number | null }) => {
    if (delta == null) return null;
    const absDelta = Math.abs(delta);
    if (absDelta < 1) return (
      <span className="inline-flex items-center gap-0.5 text-[11px] font-medium" style={{ color: "var(--labs-text-muted)" }}>
        <Minus className="w-3 h-3" /> ±0
      </span>
    );
    if (delta > 0) return (
      <span className="inline-flex items-center gap-0.5 text-[11px] font-medium" style={{ color: "var(--labs-success)" }}>
        <TrendingUp className="w-3 h-3" /> +{delta}
      </span>
    );
    return (
      <span className="inline-flex items-center gap-0.5 text-[11px] font-medium" style={{ color: "var(--labs-danger)" }}>
        <TrendingDown className="w-3 h-3" /> {delta}
      </span>
    );
  };

  const AgreementBadge = ({ stdDev, count }: { stdDev: number | null; count: number }) => {
    if (stdDev == null || count < 2) return null;
    if (stdDev <= 5) return (
      <span className="labs-badge labs-badge-success text-[10px]" data-testid="badge-consensus">
        <Target className="w-3 h-3" /> Consensus
      </span>
    );
    if (stdDev > 10) return (
      <span className="labs-badge labs-badge-danger text-[10px]" data-testid="badge-debated">
        <MessageCircle className="w-3 h-3" /> Debated
      </span>
    );
    return null;
  };

  return (
    <div className="px-5 py-6 max-w-2xl mx-auto labs-fade-in">
      <button
        onClick={() => navigate(`/labs/tastings/${tastingId}`)}
        className="flex items-center gap-1.5 mb-5 text-sm transition-colors"
        style={{ color: "var(--labs-text-muted)", background: "none", border: "none", cursor: "pointer", padding: 0, fontFamily: "inherit" }}
        data-testid="results-back-btn"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to Tasting
      </button>

      <div className="mb-6 labs-stagger-1 labs-fade-in">
        <div className="flex items-start justify-between gap-3">
          <div>
            <h1
              className="labs-serif text-xl font-semibold mb-1"
              style={{ color: "var(--labs-text)" }}
              data-testid="results-title"
            >
              {tasting.title}
            </h1>
            <div className="flex items-center gap-2 flex-wrap">
              <p className="text-sm" style={{ color: "var(--labs-text-muted)" }}>
                {tasting.date} · {tasting.location}
              </p>
          {tasting.guidedMode && (
            <span
              className="labs-badge text-[10px]"
              style={{ background: "var(--labs-info-muted)", color: "var(--labs-info)" }}
              data-testid="results-guided-badge"
            >
              Guided Tasting
            </span>
          )}
            </div>
          </div>
          {sorted.length > 0 && (
            <LabsExportDropdown tastingId={tastingId} tasting={tasting} whiskyResults={whiskyResults} />
          )}
        </div>
      </div>

      <div
        className="labs-card-elevated p-5 mb-6 labs-stagger-2 labs-fade-in"
        data-testid="results-summary-card"
      >
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-4 h-4" style={{ color: "var(--labs-accent)" }} />
          <span className="labs-section-label" style={{ marginBottom: 0 }}>Session Summary</span>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
          <div className="text-center">
            <Wine className="w-4 h-4 mx-auto mb-1" style={{ color: "var(--labs-accent)" }} />
            <p className="text-lg font-bold" style={{ color: "var(--labs-text)" }}>{whiskies?.length || 0}</p>
            <p className="text-[11px]" style={{ color: "var(--labs-text-muted)" }}>Whiskies</p>
          </div>
          <div className="text-center">
            <Users className="w-4 h-4 mx-auto mb-1" style={{ color: "var(--labs-accent)" }} />
            <p className="text-lg font-bold" style={{ color: "var(--labs-text)" }}>{participantCount}</p>
            <p className="text-[11px]" style={{ color: "var(--labs-text-muted)" }}>Tasters</p>
          </div>
          <div className="text-center">
            <BarChart3 className="w-4 h-4 mx-auto mb-1" style={{ color: "var(--labs-accent)" }} />
            <p className="text-lg font-bold" style={{ color: "var(--labs-text)" }}>{summaryData.groupAvg ?? "—"}</p>
            <p className="text-[11px]" style={{ color: "var(--labs-text-muted)" }}>Group Avg</p>
          </div>
          <div className="text-center">
            <Star className="w-4 h-4 mx-auto mb-1" style={{ color: "var(--labs-accent)" }} />
            <p className="text-lg font-bold" style={{ color: "var(--labs-text)" }}>{summaryData.userAvg ?? "—"}</p>
            <p className="text-[11px]" style={{ color: "var(--labs-text-muted)" }}>Your Avg</p>
          </div>
        </div>

        {(summaryData.mostAgreed || summaryData.mostDebated) && (
          <div
            className="pt-3 grid grid-cols-1 sm:grid-cols-2 gap-3"
            style={{ borderTop: "1px solid var(--labs-border-subtle)" }}
          >
            {summaryData.mostAgreed && (
              <div className="flex items-start gap-2" data-testid="results-most-agreed">
                <Target className="w-4 h-4 mt-0.5 flex-shrink-0" style={{ color: "var(--labs-success)" }} />
                <div>
                  <p className="text-[11px] font-medium" style={{ color: "var(--labs-success)" }}>Most Agreed</p>
                  <p className="text-sm font-medium truncate" style={{ color: "var(--labs-text)" }}>
                    {summaryData.mostAgreed.name || "Unknown"}
                  </p>
                </div>
              </div>
            )}
            {summaryData.mostDebated && (
              <div className="flex items-start gap-2" data-testid="results-most-debated">
                <MessageCircle className="w-4 h-4 mt-0.5 flex-shrink-0" style={{ color: "var(--labs-danger)" }} />
                <div>
                  <p className="text-[11px] font-medium" style={{ color: "var(--labs-danger)" }}>Most Debated</p>
                  <p className="text-sm font-medium truncate" style={{ color: "var(--labs-text)" }}>
                    {summaryData.mostDebated.name || "Unknown"}
                  </p>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {topWhisky && topWhisky.avgOverall != null && (
        <div
          className="labs-card-elevated p-5 mb-6 labs-stagger-3 labs-fade-in"
          data-testid="results-top-whisky"
        >
          <div className="flex items-center gap-2 mb-3">
            <Trophy className="w-5 h-5" style={{ color: "var(--labs-accent)" }} />
            <span className="labs-section-label" style={{ marginBottom: 0 }}>
              Top Rated
            </span>
          </div>
          <div className="flex items-center justify-between">
            <div>
              <p className="labs-serif text-base font-semibold" style={{ color: "var(--labs-text)" }}>
                {topWhisky.name || "Unknown"}
              </p>
              <p className="text-xs mt-0.5" style={{ color: "var(--labs-text-muted)" }}>
                {[topWhisky.distillery, topWhisky.age ? `${topWhisky.age}y` : null, topWhisky.abv ? `${topWhisky.abv}%` : null]
                  .filter(Boolean)
                  .join(" · ")}
              </p>
            </div>
            <div className="text-right">
              <p className="text-2xl font-bold" style={{ color: "var(--labs-accent)" }}>
                {topWhisky.avgOverall}
              </p>
              <p className="text-[10px]" style={{ color: "var(--labs-text-muted)" }}>avg. score</p>
            </div>
          </div>
        </div>
      )}

      {summaryData.myHighlights.length > 0 && (
        <div className="mb-6 labs-fade-in">
          <div className="labs-section-label flex items-center gap-1.5">
            <TrendingUp className="w-3.5 h-3.5" style={{ color: "var(--labs-success)" }} />
            Your Highlights
          </div>
          <div className="space-y-2">
            {summaryData.myHighlights.slice(0, 3).map(w => (
              <div key={w.id} className="labs-card p-3 flex items-center justify-between" data-testid={`results-highlight-${w.id}`}>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium truncate" style={{ color: "var(--labs-text)" }}>{w.name || "Unknown"}</p>
                  <p className="text-xs" style={{ color: "var(--labs-text-muted)" }}>
                    You: {w.myRating?.overall} · Group: {w.avgOverall}
                  </p>
                </div>
                <DeltaIndicator delta={w.myDelta} />
              </div>
            ))}
          </div>
        </div>
      )}

      {summaryData.consensusWhiskies.length > 0 && (
        <div className="mb-6 labs-fade-in">
          <div className="labs-section-label flex items-center gap-1.5">
            <Target className="w-3.5 h-3.5" style={{ color: "var(--labs-success)" }} />
            Group Consensus
          </div>
          <div className="space-y-2">
            {summaryData.consensusWhiskies.slice(0, 3).map(w => (
              <div key={w.id} className="labs-card p-3 flex items-center justify-between" data-testid={`results-consensus-${w.id}`}>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium truncate" style={{ color: "var(--labs-text)" }}>{w.name || "Unknown"}</p>
                  <p className="text-xs" style={{ color: "var(--labs-text-muted)" }}>
                    Avg: {w.avgOverall} · Range: {w.overallRange.min}–{w.overallRange.max}
                  </p>
                </div>
                <AgreementBadge stdDev={w.overallStdDev} count={w.ratingCount} />
              </div>
            ))}
          </div>
        </div>
      )}

      {summaryData.debatedWhiskies.length > 0 && (
        <div className="mb-6 labs-fade-in">
          <div className="labs-section-label flex items-center gap-1.5">
            <MessageCircle className="w-3.5 h-3.5" style={{ color: "var(--labs-danger)" }} />
            Most Debated
          </div>
          <div className="space-y-2">
            {summaryData.debatedWhiskies.slice(0, 3).map(w => (
              <div key={w.id} className="labs-card p-3 flex items-center justify-between" data-testid={`results-debated-${w.id}`}>
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-medium truncate" style={{ color: "var(--labs-text)" }}>{w.name || "Unknown"}</p>
                  <p className="text-xs" style={{ color: "var(--labs-text-muted)" }}>
                    Avg: {w.avgOverall} · Range: {w.overallRange.min}–{w.overallRange.max}
                  </p>
                </div>
                <AgreementBadge stdDev={w.overallStdDev} count={w.ratingCount} />
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="labs-section-label labs-fade-in">Rankings</div>

      <div className="space-y-2 mb-8 labs-fade-in">
        {sorted.map((w, idx) => {
          const isExpanded = expandedWhisky === w.id;
          const medal = idx === 0 ? "🥇" : idx === 1 ? "🥈" : idx === 2 ? "🥉" : null;

          return (
            <div key={w.id} className="labs-card overflow-hidden" data-testid={`results-whisky-${w.id}`}>
              <div
                className="flex items-center gap-3 p-4 cursor-pointer"
                onClick={() => toggleExpand(w.id)}
              >
                <div
                  className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 text-sm font-bold"
                  style={{
                    background: idx < 3 ? "var(--labs-accent-muted)" : "var(--labs-surface-elevated)",
                    color: idx < 3 ? "var(--labs-accent)" : "var(--labs-text-muted)",
                  }}
                >
                  {medal || idx + 1}
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <p className="text-sm font-medium truncate" style={{ color: "var(--labs-text)" }}>
                      {w.name || "Unknown"}
                    </p>
                    <AgreementBadge stdDev={w.overallStdDev} count={w.ratingCount} />
                  </div>
                  <div className="flex items-center gap-2">
                    <p className="text-xs truncate" style={{ color: "var(--labs-text-muted)" }}>
                      {[w.distillery, w.region].filter(Boolean).join(" · ") || "—"}
                    </p>
                    {w.myDelta != null && (
                      <DeltaIndicator delta={w.myDelta} />
                    )}
                  </div>
                </div>

                <div className="flex items-center gap-2 flex-shrink-0">
                  {w.avgOverall != null ? (
                    <span className="text-base font-bold" style={{ color: "var(--labs-accent)" }}>
                      {w.avgOverall}
                    </span>
                  ) : (
                    <span className="text-xs" style={{ color: "var(--labs-text-muted)" }}>—</span>
                  )}
                  {isExpanded ? (
                    <ChevronUp className="w-4 h-4" style={{ color: "var(--labs-text-muted)" }} />
                  ) : (
                    <ChevronDown className="w-4 h-4" style={{ color: "var(--labs-text-muted)" }} />
                  )}
                </div>
              </div>

              {isExpanded && (
                <div
                  className="px-4 pb-4 pt-1"
                  style={{ borderTop: "1px solid var(--labs-border-subtle)" }}
                >
                  <div className="grid grid-cols-2 gap-3 mb-3">
                    {[
                      { label: "Nose", value: w.avgNose },
                      { label: "Taste", value: w.avgTaste },
                      { label: "Finish", value: w.avgFinish },
                      { label: "Balance", value: w.avgBalance },
                    ].map((dim) => (
                      <div key={dim.label} className="flex items-center justify-between">
                        <span className="text-xs" style={{ color: "var(--labs-text-muted)" }}>
                          {dim.label}
                        </span>
                        <span className="text-sm font-semibold" style={{ color: "var(--labs-text-secondary)" }}>
                          {dim.value != null ? dim.value : "—"}
                        </span>
                      </div>
                    ))}
                  </div>

                  <div className="flex items-center justify-between text-xs mb-2" style={{ color: "var(--labs-text-muted)" }}>
                    <span>{w.ratingCount} rating{w.ratingCount !== 1 ? "s" : ""}</span>
                    {w.abv && <span>{w.abv}% ABV</span>}
                    {w.age && <span>{w.age} years</span>}
                  </div>

                  {w.overallRange.min != null && w.overallRange.max != null && w.ratingCount >= 2 && (
                    <div
                      className="p-3 rounded-lg mb-3"
                      style={{ background: "var(--labs-surface-elevated)" }}
                      data-testid={`results-variance-${w.id}`}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-[11px] font-medium" style={{ color: "var(--labs-text-muted)" }}>Score Range</span>
                        <span className="text-[11px]" style={{ color: "var(--labs-text-muted)" }}>
                          Spread: {w.overallRange.spread}
                        </span>
                      </div>
                      <div className="relative h-2 rounded-full" style={{ background: "var(--labs-border)" }}>
                        <div
                          className="absolute h-full rounded-full"
                          style={{
                            background: "var(--labs-accent)",
                            opacity: 0.4,
                            left: `${w.overallRange.min}%`,
                            width: `${Math.max(w.overallRange.max - w.overallRange.min, 2)}%`,
                          }}
                        />
                      </div>
                      <div className="flex items-center justify-between mt-1.5">
                        <span className="text-[11px] font-semibold" style={{ color: "var(--labs-text-secondary)" }}>
                          {w.overallRange.min}
                        </span>
                        <span className="text-[11px] font-semibold" style={{ color: "var(--labs-text-secondary)" }}>
                          {w.overallRange.max}
                        </span>
                      </div>
                    </div>
                  )}

                  {w.caskType && (
                    <span className="labs-badge labs-badge-accent text-[11px]">{w.caskType}</span>
                  )}

                  {w.myRating && (
                    <div
                      className="mt-3 p-3 rounded-lg"
                      style={{ background: "var(--labs-accent-glow)", border: "1px solid var(--labs-border-subtle)" }}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-1.5">
                          <Star className="w-3.5 h-3.5" style={{ color: "var(--labs-accent)" }} />
                          <span className="text-xs font-medium" style={{ color: "var(--labs-accent)" }}>
                            Your Rating
                          </span>
                        </div>
                        {w.myDelta != null && (
                          <div className="flex items-center gap-1">
                            <span className="text-[10px]" style={{ color: "var(--labs-text-muted)" }}>vs Group:</span>
                            <DeltaIndicator delta={w.myDelta} />
                          </div>
                        )}
                      </div>
                      <div className="grid grid-cols-5 gap-2 text-center">
                        {[
                          { label: "N", value: w.myRating.nose },
                          { label: "T", value: w.myRating.taste },
                          { label: "F", value: w.myRating.finish },
                          { label: "B", value: w.myRating.balance },
                          { label: "Ø", value: w.myRating.overall },
                        ].map((d) => (
                          <div key={d.label}>
                            <p className="text-[10px]" style={{ color: "var(--labs-text-muted)" }}>{d.label}</p>
                            <p className="text-sm font-semibold" style={{ color: "var(--labs-text)" }}>
                              {d.value ?? "—"}
                            </p>
                          </div>
                        ))}
                      </div>
                      {w.myRating.notes && (
                        <p className="text-xs mt-2 italic" style={{ color: "var(--labs-text-secondary)" }}>
                          "{w.myRating.notes}"
                        </p>
                      )}
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {sorted.length === 0 && (
        <div className="labs-empty">
          <Wine className="w-10 h-10 mb-3" style={{ color: "var(--labs-text-muted)" }} />
          <p className="text-sm font-medium mb-1" style={{ color: "var(--labs-text-secondary)" }}>
            No results yet
          </p>
          <p className="text-xs" style={{ color: "var(--labs-text-muted)" }}>
            Results will appear once participants have submitted their ratings
          </p>
        </div>
      )}

      <div className="flex justify-center gap-3 pb-8">
        <button
          className="labs-btn-secondary"
          onClick={() => navigate("/labs/tastings")}
          data-testid="results-all-tastings"
        >
          All Tastings
        </button>
        <button
          className="labs-btn-ghost"
          onClick={() => navigate(`/labs/tastings/${tastingId}`)}
          data-testid="results-tasting-detail"
        >
          Tasting Details
        </button>
      </div>
    </div>
  );
}