import jsPDF from "jspdf";
import { saveJsPdf } from "@/lib/pdf";
import type { ConnoisseurReport } from "@shared/schema";

interface ConnoisseurPdfOptions {
  report: ConnoisseurReport;
  participantName: string;
  language: string;
  participantPhotoUrl?: string | null;
}

type RGB = [number, number, number];

const ACCENT: RGB = [180, 130, 30];
const PRIMARY: RGB = [30, 30, 32];
const SECONDARY: RGB = [100, 100, 110];
const BG: RGB = [252, 251, 248];
const HIGHLIGHT_BG: RGB = [255, 248, 230];

function formatDate(date: Date | string | null, lang: string): string {
  if (!date) return "";
  try {
    return new Date(date).toLocaleDateString(lang === "de" ? "de-DE" : "en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  } catch {
    return String(date);
  }
}

function parseMarkdownLines(md: string): { type: string; text: string }[] {
  const lines = md.split("\n");
  const result: { type: string; text: string }[] = [];

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.startsWith("### ")) {
      result.push({ type: "h3", text: line.slice(4).trim() });
    } else if (line.startsWith("## ")) {
      result.push({ type: "h2", text: line.slice(3).trim() });
    } else if (line.startsWith("# ")) {
      result.push({ type: "h1", text: line.slice(2).trim() });
    } else if (line.startsWith("---") || line.startsWith("***")) {
      result.push({ type: "hr", text: "" });
    } else if (line.match(/^[-*]\s+/)) {
      result.push({ type: "bullet", text: line.replace(/^[-*]\s+/, "").trim() });
    } else if (line.trim() === "") {
      result.push({ type: "blank", text: "" });
    } else {
      result.push({ type: "p", text: line.trim() });
    }
  }
  return result;
}

async function loadImageAsBase64(url: string): Promise<string | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const blob = await res.blob();
    const objectUrl = URL.createObjectURL(blob);
    try {
      const img = await new Promise<HTMLImageElement>((resolve, reject) => {
        const i = new Image();
        i.onload = () => resolve(i);
        i.onerror = reject;
        i.src = objectUrl;
      });
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext("2d");
      if (!ctx) return null;
      ctx.fillStyle = "#fff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0);
      return canvas.toDataURL("image/jpeg", 0.9);
    } finally {
      URL.revokeObjectURL(objectUrl);
    }
  } catch { return null; }
}

function stripMd(text: string): string {
  return text.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").replace(/__(.*?)__/g, "$1").replace(/_(.*?)_/g, "$1");
}

function renderBoldSegments(doc: jsPDF, text: string, x: number, y: number, maxW: number, color: RGB) {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  let cx = x;
  for (const part of parts) {
    if (part.startsWith("**") && part.endsWith("**")) {
      const clean = part.slice(2, -2);
      doc.setFont("helvetica", "bold");
      const lines = doc.splitTextToSize(clean, maxW - (cx - x));
      doc.setTextColor(...color);
      doc.text(lines[0] || "", cx, y);
      cx += doc.getTextWidth(lines[0] || "");
      doc.setFont("helvetica", "normal");
    } else if (part) {
      const lines = doc.splitTextToSize(part, maxW - (cx - x));
      doc.setTextColor(...color);
      doc.text(lines[0] || "", cx, y);
      cx += doc.getTextWidth(lines[0] || "");
    }
  }
}

export async function generateConnoisseurReportPdf(options: ConnoisseurPdfOptions): Promise<void> {
  const { report, participantName, language, participantPhotoUrl } = options;

  const pageW = 210;
  const pageH = 297;
  const marginX = 22;
  const contentW = pageW - marginX * 2;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  let pageNum = 1;

  const addPageBg = () => {
    doc.setFillColor(...BG);
    doc.rect(0, 0, pageW, pageH, "F");
  };

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SECONDARY);
    doc.text("Generated by CaskSense — Where tasting becomes reflection.", marginX, pageH - 10);
    doc.text(`${pageNum}`, pageW - marginX, pageH - 10, { align: "right" });
  };

  const checkPageBreak = (y: number, needed: number): number => {
    if (y + needed > pageH - 20) {
      addFooter();
      pageNum++;
      doc.addPage();
      addPageBg();
      return 25;
    }
    return y;
  };

  addPageBg();

  let y = 35;

  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(0.8);
  doc.line(marginX, y, pageW - marginX, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...SECONDARY);
  doc.text("C A S K S E N S E", marginX, y);
  y += 12;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(...PRIMARY);
  const titleText = language === "de" ? "Connoisseur-Bericht" : "Connoisseur Report";
  doc.text(titleText, marginX, y);
  y += 12;

  let photoDataUrl: string | null = null;
  if (participantPhotoUrl) {
    photoDataUrl = await loadImageAsBase64(participantPhotoUrl);
  }

  if (photoDataUrl) {
    try {
      doc.addImage(photoDataUrl, "JPEG", marginX, y - 5, 14, 14, undefined, "FAST");
    } catch {}
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.setTextColor(...SECONDARY);
    doc.text(participantName, marginX + 18, y + 3);
    y += 14;
  } else {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.setTextColor(...SECONDARY);
    doc.text(participantName, marginX, y);
    y += 8;
  }

  doc.setFontSize(10);
  doc.setTextColor(...SECONDARY);
  const dateStr = formatDate(report.generatedAt, language);
  doc.text(dateStr, marginX, y);
  y += 6;

  doc.setDrawColor(...ACCENT);
  doc.setLineWidth(0.4);
  doc.line(marginX, y, pageW - marginX, y);
  y += 12;

  if (report.summary) {
    y = checkPageBreak(y, 30);

    const summaryLines = doc.splitTextToSize(stripMd(report.summary), contentW - 12);
    const boxH = summaryLines.length * 5 + 12;

    doc.setFillColor(...HIGHLIGHT_BG);
    doc.setDrawColor(...ACCENT);
    doc.setLineWidth(0.5);
    doc.roundedRect(marginX, y, contentW, boxH, 2, 2, "FD");

    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(...PRIMARY);
    doc.text(summaryLines, marginX + 6, y + 8);

    y += boxH + 10;
  }

  const parsed = parseMarkdownLines(report.reportContent);

  for (const line of parsed) {
    switch (line.type) {
      case "h1": {
        y = checkPageBreak(y, 14);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.setTextColor(...PRIMARY);
        doc.text(stripMd(line.text), marginX, y);
        y += 10;
        break;
      }
      case "h2": {
        y = checkPageBreak(y, 14);
        y += 3;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(...PRIMARY);
        doc.text(stripMd(line.text), marginX, y);
        y += 3;
        doc.setDrawColor(...ACCENT);
        doc.setLineWidth(0.2);
        doc.line(marginX, y, marginX + 50, y);
        y += 6;
        break;
      }
      case "h3": {
        y = checkPageBreak(y, 12);
        y += 2;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(...PRIMARY);
        doc.text(stripMd(line.text), marginX, y);
        y += 6;
        break;
      }
      case "hr": {
        y = checkPageBreak(y, 8);
        y += 2;
        doc.setDrawColor(...SECONDARY);
        doc.setLineWidth(0.15);
        doc.line(marginX + 20, y, pageW - marginX - 20, y);
        y += 6;
        break;
      }
      case "bullet": {
        y = checkPageBreak(y, 8);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        const bulletLines = doc.splitTextToSize(stripMd(line.text), contentW - 8);
        doc.setTextColor(...SECONDARY);
        doc.text("•", marginX + 2, y);
        doc.setTextColor(...PRIMARY);
        doc.text(bulletLines, marginX + 7, y);
        y += bulletLines.length * 4.5 + 1.5;
        break;
      }
      case "p": {
        const plainText = stripMd(line.text);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        const wrapped = doc.splitTextToSize(plainText, contentW);
        y = checkPageBreak(y, wrapped.length * 4.5 + 2);
        doc.setTextColor(...PRIMARY);
        if (line.text.includes("**")) {
          for (let i = 0; i < wrapped.length; i++) {
            doc.text(wrapped[i], marginX, y);
            y += 4.5;
          }
        } else {
          doc.text(wrapped, marginX, y);
          y += wrapped.length * 4.5;
        }
        y += 1.5;
        break;
      }
      case "blank": {
        y += 3;
        break;
      }
    }
  }

  const snapshot = report.dataSnapshot as Record<string, unknown> | null;
  if (snapshot && typeof snapshot === "object" && Object.keys(snapshot).length > 0) {
    y = checkPageBreak(y, 30);
    y += 6;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...PRIMARY);
    const metricsTitle = language === "de" ? "Kennzahlen zum Zeitpunkt der Erstellung" : "Metrics Snapshot";
    doc.text(metricsTitle, marginX, y);
    y += 2;
    doc.setDrawColor(...ACCENT);
    doc.setLineWidth(0.2);
    doc.line(marginX, y, marginX + 50, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);

    const metricLabels: Record<string, Record<string, string>> = {
      totalRatings: { en: "Total Ratings", de: "Bewertungen gesamt" },
      totalTastings: { en: "Total Tastings", de: "Tastings gesamt" },
      totalJournalEntries: { en: "Diary Entries", de: "Diary-Einträge" },
      topRegion: { en: "Top Region", de: "Top-Region" },
      topRegionCount: { en: "Top Region Count", de: "Top-Region Anzahl" },
      collectionSize: { en: "Collection Size", de: "Sammlungsgröße" },
      smokeAffinityIndex: { en: "Smoke Affinity", de: "Rauch-Affinität" },
      sweetnessBias: { en: "Sweetness Bias", de: "Süße-Neigung" },
      explorationIndex: { en: "Exploration Index", de: "Erkundungsindex" },
      ratingStabilityScore: { en: "Rating Stability", de: "Bewertungsstabilität" },
      groupAvgOverall: { en: "Group Average", de: "Gruppen-Durchschnitt" },
      vsGroupDelta: { en: "vs. Group Delta", de: "Abweichung zur Gruppe" },
      tasteTwinsCount: { en: "Taste Twins", de: "Geschmackszwillinge" },
      topTasteTwin: { en: "Closest Taste Twin", de: "Engster Geschmackszwilling" },
      topTasteTwinCorrelation: { en: "Twin Correlation", de: "Zwillings-Korrelation" },
    };

    const aiTextFields = new Set([
      "reportEn", "reportDe", "summaryEn", "summaryDe",
      "palateProfileEn", "palateProfileDe",
      "tastingHighlightsEn", "tastingHighlightsDe",
      "recommendationEn", "recommendationDe",
      "quoteEn", "quoteDe",
    ]);

    const specialFields = new Set(["highestWhisky", "lowestWhisky", "groupAvgScores"]);

    const formatValue = (val: unknown): string => {
      if (typeof val === "number") {
        return Number.isInteger(val) ? String(val) : val.toFixed(2);
      }
      return String(val);
    };

    const renderMetricRow = (label: string, value: string) => {
      y = checkPageBreak(y, 8);
      const xPos = marginX + col * colW;
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...SECONDARY);
      doc.text(`${label}:`, xPos, y);
      const labelW = doc.getTextWidth(`${label}: `);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...PRIMARY);
      doc.text(value, xPos + labelW, y);
      col++;
      if (col >= 2) {
        col = 0;
        y += 6;
      }
    };

    const colW = contentW / 2;
    let col = 0;

    for (const [key, val] of Object.entries(snapshot)) {
      if (val === null || val === undefined) continue;
      if (aiTextFields.has(key)) continue;

      if (key === "highestWhisky" && val && typeof val === "object") {
        const hw = val as Record<string, unknown>;
        if (hw.name) {
          const label = language === "de" ? "Höchstbewerteter Whisky" : "Highest Rated Whisky";
          const score = hw.score != null ? ` (${formatValue(hw.score)})` : "";
          renderMetricRow(label, `${hw.name}${score}`);
        }
        continue;
      }

      if (key === "lowestWhisky" && val && typeof val === "object") {
        const lw = val as Record<string, unknown>;
        if (lw.name) {
          const label = language === "de" ? "Niedrigstbewerteter Whisky" : "Lowest Rated Whisky";
          const score = lw.score != null ? ` (${formatValue(lw.score)})` : "";
          renderMetricRow(label, `${lw.name}${score}`);
        }
        continue;
      }

      if (key === "groupAvgScores" && val && typeof val === "object") {
        const scores = val as Record<string, unknown>;
        const scoreLabels: Record<string, Record<string, string>> = {
          nose: { en: "Group Avg Nose", de: "Gruppen-Ø Nase" },
          taste: { en: "Group Avg Taste", de: "Gruppen-Ø Geschmack" },
          finish: { en: "Group Avg Finish", de: "Gruppen-Ø Finish" },
          overall: { en: "Group Avg Overall", de: "Gruppen-Ø Gesamt" },
        };
        for (const [sk, sv] of Object.entries(scores)) {
          if (sv == null || typeof sv !== "number") continue;
          const sLabel = scoreLabels[sk]?.[language] || scoreLabels[sk]?.en || sk;
          renderMetricRow(sLabel, formatValue(sv));
        }
        continue;
      }

      if (!metricLabels[key] && !specialFields.has(key)) continue;
      if (typeof val === "object") continue;

      const label = metricLabels[key]?.[language] || metricLabels[key]?.en || key;
      renderMetricRow(label, formatValue(val));
    }
    if (col !== 0) y += 6;
  }

  addFooter();

  const safeName = participantName.replace(/[^a-zA-Z0-9äöüÄÖÜß\s]/g, "").replace(/\s+/g, "_");
  const filename = `CaskSense_Connoisseur_${safeName}_${new Date().toISOString().slice(0, 10)}.pdf`;
  saveJsPdf(doc, filename);
}
